before_commands:
    - pip3 install cleo

build:
    dependencies:
        before:
          - pip3 install cleo
          - pip3 install coverage
          - pip3 install psycopg2

    tests:
        before:
          - psql -c "create user test with password 'test';" -U postgres
          - psql -c "create database test owner=test;" -U postgres
          - psql -c "create schema test authorization test;" -U postgres test
          - cat test/ddl/create_tables.sql | psql -Utest test

        override:
            -
                command: coverage run -m unittest discover -s test -p *Test.py
                coverage:
                    file: '.coverage'
                    config_file: '.coveragerc'
                    format: 'py-cc'

