filter:
  excluded_paths:
    - test/*

build:
  dependencies:
    before:
      - pip3 install cleo==0.6.8
      - pip3 install coverage
      - pip3 install psycopg2
      - pip3 install PyStratum-Backend
      - pip3 install PyStratum-Cli
      - pip3 install PyStratum-Common
      - pip3 install PyStratum-Middle

  nodes:
    analysis:
      tests:
        before:
          - sudo -u postgres psql -c "create user test with password 'test';"
          - sudo -u postgres psql -c "create database test owner=test;"
          - sudo -u postgres psql -c "create schema test authorization test;" -U postgres -d test
        override:
          - command: python3 -m unittest discover -s test -p *Test.py
            coverage:
              file: '.coverage'
              config_file: '.coveragerc'
              format: 'py-cc'
          - py-scrutinizer-run