filter:
  excluded_paths:
    - test/*

build:
  dependencies:
    before:
      - pip3 install cleo
      - pip3 install coverage
      - pip3 install psycopg2
      - pip3 install PyStratum-Backend
      - pip3 install PyStratum-Cli
      - pip3 install PyStratum-Common
      - pip3 install PyStratum-Middle

  nodes:
    analysis:
      tests:
        before:
          - psql -c "create user test with password 'test';"
          - psql -c "create database test owner=test;"
          - psql -c "create schema test authorization test;" test
        override:
          - command: bin/phing unit
            coverage:
              file: '.coverage'
              config_file: '.coveragerc'
              format: 'py-cc'
          - py-scrutinizer-run
          