before_commands:
    - sudo pip3 install cleo
    - sudo pip3 install coverage
    - sudo pip3 install psycopg2
    - sudo pip3 install pystartum

build:
    dependencies:
        before:
          - pip3 install cleo
          - pip3 install coverage
          - pip3 install psycopg2
          - pip3 install pystartum

    tests:
        before:
          - psql -c "create user test with password 'test';"
          - psql -c "create database test owner=test;"
          - psql -c "create schema test authorization test;" test

        override:
            -
                command: coverage run -m unittest discover -s test -p *Test.py
                coverage:
                    file: '.coverage'
                    config_file: '.coveragerc'
                    format: 'py-cc'

