dist: xenial

language: python
python:
  - '3.6'
  - '3.7'

sudo: true

services:
  - postgresql
  
install:
  - cd $HOME
  - pip3 install psycopg2-binary
  - pip3 install pystratum

before_script:
  - psql --version
  - psql -c "create user test with password 'test';" -U postgres
  - psql -c "create database test owner=test;" -U postgres
  - psql -c "create schema test authorization test;" -U postgres test

script: 
  - cd $TRAVIS_BUILD_DIR
  - python3 -m unittest discover -s pystratum_test -p *Test.py
