dist: xenial

language: python
python:
  - '3.6'
  - '3.7'
  - '3.8'

sudo: true

services:
  - postgresql
  
install:
  - cd $HOME
  - pip3 install psycopg2-binary
  - pip3 install PyStratum-Backend
  - pip3 install PyStratum-Cli
  - pip3 install PyStratum-Common
  - pip3 install PyStratum-Middle

before_script:
  - psql --version
  - psql -c "create user test with password 'test';" -U postgres
  - psql -c "create database test owner=test;" -U postgres
  - psql -c "create schema test authorization test;" -U postgres test
  - cat test/ddl/create_tables.sql | psql -Utest test

script: 
  - cd $TRAVIS_BUILD_DIR
  - python3 -m unittest discover -s test -p *Test.py
