language: python
python:
  - '3.4'
  - '3.5'
  - '3.6'

sudo: true

addons:
  mariadb: 10.1
  
install:
  - cd $HOME
  - pip3 install cleo
  - pip3 install psycopg2
  - pip3 install pystratum

before_script:
  - psql --version
  - psql -c "create user test with password 'test';" -U postgres
  - psql -c "create database test owner=test;" -U postgres
  - psql -c "create schema test authorization test;" -U postgres test

script: 
  - cd $TRAVIS_BUILD_DIR
  - python3 -m unittest discover -s pystratum_test -p *Test.py
