/**
 * Creates a temporary table for log messages.
 */
create function stratum_log_init()
returns void
as $$
-- type: hidden
begin
  drop table if exists tmp_stratum_log;

  create temporary table tmp_stratum_log
  (
    tmp_id      serial       not null,
    tmp_time    timestamp(0) not null,
    tmp_message varchar(1024),
    constraint pk_tmp_log primary key (tmp_id)
  );
end;
$$ language plpgsql;